### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by nickvanderstel** [zpconn/language-tcl#12] opened 2015-05-20 19:10 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\nicholasvanderstel\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:584:9)
<unknown> (C:\Users\nicholasvanderstel\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:184:43)
Package.measure (C:\Users\nicholasvanderstel\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:163:15)
Package.load (C:\Users\nicholasvanderstel\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package.js:177:12)
PackageManager.loadPackage (C:\Users\nicholasvanderstel\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package-manager.js:355:14)
PackageManager.loadPackages (C:\Users\nicholasvanderstel\AppData\Local\atom\app-0.200.0\resources\app.asar\src\package-manager.js:325:14)
```

**Comment by xeron** [comment] 2015-05-24 06:15
Duplicate of https://github.com/zpconn/language-tcl/issues/9

**Comment by zpconn** [comment] 2015-05-25 05:50
Fixed with https://github.com/zpconn/language-tcl/pull/11. Thanks @xeron!

**Closed by zpconn** 2015-05-25 05:50 UTC
